steps:
  # Step to build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/genial-post-457002-n2/loan-predictor-app/loan-predictor',
      '.'
    ]

  # Step to push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/genial-post-457002-n2/loan-predictor-app/loan-predictor'
    ]

  # Step to deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'loan-predictor'
      - '--image'
      - 'us-central1-docker.pkg.dev/genial-post-457002-n2/loan-predictor-app/loan-predictor'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

  # Optional step
  - name: 'bash'
    args: ['-c', 'echo Hello from Cloud Build! ✅']

images:
  - 'us-central1-docker.pkg.dev/genial-post-457002-n2/loan-predictor-app/loan-predictor'

logsBucket: 'gs://loan-pred-bucket'

serviceAccount: 'loan-pred-account@genial-post-457002-n2.iam.gserviceaccount.com'

options:
  logging: GCS_ONLY
